import type { LanguageText } from '@/types/resume'

// 语言文本定义
export const languageTexts: Record<'en' | 'zh', LanguageText> = {
  en: {
    personalInfo: 'Personal Information',
    fullName: 'Full Name',
    title: 'Title',
    email: 'Email',
    phone: 'Phone',
    professionalSummary: 'Professional Summary',
    summary: 'Summary',
    workExperience: 'Work Experience',
    company: 'Company',
    position: 'Position',
    duration: 'Duration',
    description: 'Description',
    education: 'Education',
    school: 'School',
    degree: 'Degree',
    year: 'Year',
    skills: 'Skills',
    addExperience: 'Add Experience',
    addEducation: 'Add Education',
    remove: 'Remove',
    generatePDF: 'Generate PDF',
    generateWord: 'Generate Word',
    reset: 'Reset',
    manageTemplates: 'Manage Templates',
    saveAsTemplate: 'Save as Template',
    templateName: 'Template Name',
    createTime: 'Create Time',
    actions: 'Actions',
    load: 'Load',
    delete: 'Delete',
    noTemplates: 'No templates yet',
    generateImage: 'Save as Image',
    customSections: 'Custom Sections',
    addCustomSection: 'Add Custom Section',
    sectionTitle: 'Section Title',
    sectionContent: 'Section Content'
  },
  zh: {
    personalInfo: '个人信息',
    fullName: '姓名',
    title: '职位',
    email: '邮箱',
    phone: '电话',
    professionalSummary: '专业总结',
    summary: '总结',
    workExperience: '工作经验',
    company: '公司',
    position: '职位',
    duration: '时间段',
    description: '描述',
    education: '教育经历',
    school: '学校',
    degree: '学位',
    year: '年份',
    skills: '技能',
    addExperience: '添加工作经验',
    addEducation: '添加教育经历',
    remove: '删除',
    generatePDF: '生成PDF',
    generateWord: '生成Word',
    reset: '重置',
    manageTemplates: '管理模板',
    saveAsTemplate: '保存为模板',
    templateName: '模板名称',
    createTime: '创建时间',
    actions: '操作',
    load: '加载',
    delete: '删除',
    noTemplates: '暂无模板',
    generateImage: '保存为图片',
    customSections: '自定义模块',
    addCustomSection: '添加自定义模块',
    sectionTitle: '模块标题',
    sectionContent: '模块内容'
  }
}
